### ISSUE TITLE
request

### ISSUE THREAD

**Issue by martin-ivanov-IT** [Thommynator/AgeOfWarGame#63]
Hi, I just started creating my own version of War of Age using C and SDL2
I can not find any 2d assets for the game
maybe you can share your assets :)
will be great

**Comment by Thommynator** [comment]
Hi @martin-ivanov-IT,
I drew the [soldier assets](https://github.com/Thommynator/AgeOfWarGame/tree/%2361-epoch-visualizations/AgeOfWarGame/Assets/Sprites/Soldiers/Epoch1) myself. Feel free to take them for your game if you want. 
Notice that it's just for the first time epoch so far, i.e. a lot of assets are missing, but I'm not sure if I will continue the project.

The other assets (e.g. buildings) were taken from some free asset store website, I don't remember the page.

Would be cool to see your final product. Please share a link with me if it's done. ;)
